
version: '3.3'

services:
  backend:
    container_name: "api"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - '.:/usr/src/app/'
      - "/usr/src/app/node_modules"
    depends_on:
      - mongo
    networks:
      - api-networks
  mongo:
    container_name: db-mongo
    image: mongo:latest
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    networks:
      - api-networks
    volumes:
      - "mongo-data:/data/db"
    expose:
      - ${MONGO_PORT}
    # command: mongod --auth
networks:
  api-networks:
    driver: bridge

volumes:
  mongo-data:
    driver: "local"
